# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM node:lts-alpine

WORKDIR /app

# Copy package files
COPY package.json package-lock.json ./

# Install dependencies without running lifecycle scripts
RUN npm install --ignore-scripts

# Copy all source files
COPY . ./

# Build the project and set permissions
RUN npm run build

EXPOSE 8080

# Default command to run the MCP server
CMD ["node", "build/index.js"]
